version: '3.4'
name: coingecko-prices-collector

services:
  coingecko-collector-worker:
    image: ${DOCKER_REGISTRY-}coingecko-collector-worker
    build:
      context: .
      dockerfile: Services/Collector/CoingeckoCollector/Dockerfile

  coingecko-prices-webapi:
    image: ${DOCKER_REGISTRY-}coingecko-prices-webapi
    build:
      context: .
      dockerfile: Services/CoingeckoPrices.WebApi/Dockerfile

  zookeeper:
    container_name: coingecko-zookeeper
    image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: coingecko-kafka
    depends_on:
      - zookeeper

  kafka-create-topics-tool:
    container_name: coingecko-kafka-create-topics-tool
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic currency-coins-updated.event --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: coingecko-kafka-ui